#server:
#  port: 8080
#  profiles:
#    active: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QiNiu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 20
      max-wait-millis: 60000

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: tech.six6.mySpringBoot_001.entity

